language: objective-c
osx_image: xcode611
cache: bundler
rvm:
  - system
before_install:
  - sudo gem install bundler
  - git submodule update --init --recursive
script:
  - bundle exec rake spec
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
branches:
  except:
    - swift1p2
